#!/bin/sh
# fallocate -l 4G /swapfile
sudo dd if=/dev/zero of=/swapfile count=4000 bs=1MiB
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo "/swapfile   none    swap    sw    0   0" >> sudo /etc/fstab
